name: CI

on:
  push:
    branches: [ main ]
    pull_request:
      branches: [ main ]
      types: [ opened, synchronize ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

defaults:
  run:
    shell: bash

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose-plugin
      - name: Build and start containers with --wait flag
        run: make docker-up
      - name: Check containers
        if: ${{ inputs.debug_enabled }}
        run: make docker -- ps -a
      - name: Analyze code with PHPStan
        run: make phpstan-ci
      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3
          #        with:
        #limit-access-to-actor: true
      - name: Analyze code PHP CS Fixer
        run: make php-cs-fixer-ci
      - name: Run PHPUnit tests
        run: make phpunit-ci
      - name: Run Behat tests
        run: make behat-ci
      - name: Stop and remove containers
        if: always()
        run: make docker-down
